# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [9]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [10]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [11]:
#
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

In [12]:
chipo.describe()

          order_id     quantity
count  4622.000000  4622.000000
mean    927.254868     1.075725
std     528.890796     0.410186
min       1.000000     1.000000
25%     477.250000     1.000000
50%     926.000000     1.000000
75%    1393.000000     1.000000
max    1834.000000    15.000000

### Step 3. Name of the max valued product

In [13]:
chipo['item_price'] = chipo['item_price'].str.replace("$", "").astype(float)

In [14]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   float64
dtypes: float64(1), int64(2), str(2)
memory usage: 180.7 KB

In [15]:
chipo['item_price'].max()

np.float64(44.25)

In [17]:
str(chipo[chipo["item_price"] ==chipo["item_price"].max()]["item_name"].values[0])

'Chips and Fresh Tomato Salsa'

### Step 4. How many products cost more than $10.00?

In [19]:
chipo['unit_price'] = chipo['item_price'] / chipo['quantity']
chipo

,order_id,quantity,item_name,choice_description,item_price,unit_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39,2.39
1,1,1,Izze,[Clementine],3.39,3.39
2,1,1,Nantucket Nectar,[Apple],3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75,8.75

In [20]:
chipo[chipo["unit_price"]>10]

,order_id,quantity,item_name,choice_description,item_price,unit_price
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98,10.98
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",11.75,11.75
...,...,...,...,...,...,...
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25,11.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [24]:
chipo[chipo["unit_price"]>10]["order_id"].unique()

array([   3,    4,    7,   12,   19,   20,   21,   24,   26,   27,   28,
         30,   35,   40,   41,   43,   54,   57,   59,   60,   61,   62,
         63,   64,   65,   66,   71,   72,   73,   74,   75,   79,   80,
         83,   84,   86,   89,   90,   93,   94,   95,   99,  103,  107,
        109,  114,  123,  126,  127,  128,  129,  132,  134,  140,  144,
        146,  147,  148,  149,  152,  157,  158,  159,  163,  165,  166,
        168,  170,  171,  174,  175,  176,  177,  178,  179,  180,  186,
        189,  192,  195,  196,  198,  202,  203,  204,  205,  206,  207,
        210,  211,  212,  222,  227,  228,  229,  231,  235,  238,  239,
        241,  242,  243,  245,  248,  250,  253,  256,  258,  261,  262,
        269,  273,  277,  278,  282,  283,  284,  290,  293,  295,  297,
        300,  304,  305,  306,  308,  309,  316,  317,  324,  327,  328,
        329,  337,  338,  339,  341,  343,  347,  350,  356,  357,  358,
        360,  361,  362,  365,  367,  369,  372,  373,  374,  375,  379,
        380,  384,  387,  396,  398,  400,  404,  405,  406,  407,  408,
        409,  413,  420,  423,  428,  429,  431,  434,  435,  438,  439,
        441,  442,  443,  446,  450,  451,  452,  453,  455,  456,  459,
        461,  462,  464,  467,  468,  469,  472,  474,  478,  479,  483,
        487,  488,  491,  492,  493,  494,  498,  501,  502,  503,  504,
        507,  509,  512,  518,  519,  526,  527,  528,  529,  534,  538,
        539,  541,  545,  546,  548,  551,  552,  553,  556,  557,  561,
        562,  564,  566,  568,  570,  571,  577,  578,  579,  582,  587,
        588,  589,  593,  596,  597,  599,  600,  603,  605,  609,  612,
        618,  620,  621,  622,  627,  628,  630,  632,  635,  637,  640,
        644,  645,  646,  647,  649,  652,  653,  654,  657,  658,  659,
        660,  664,  666,  669,  672,  673,  679,  682,  684,  687,  688,
        691,  692,  693,  694,  697,  701,  702,  704,  705,  707,  708,
        712,  713,  716,  718,  719,  721,  722,  727,  731,  734,  737,
        741,  754,  755,  759,  760,  761,  766,  767,  770,  774,  777,
        780,  782,  784,  785,  790,  791,  792,  793,  794,  801,  802,
        804,  806,  807,  810,  812,  814,  815,  818,  819,  821,  823,
        825,  830,  833,  836,  837,  839,  842,  843,  845,  849,  850,
        851,  855,  856,  859,  863,  864,  865,  869,  870,  871,  872,
        874,  875,  879,  881,  885,  886,  887,  890,  893,  894,  898,
        899,  900,  901,  902,  905,  908,  914,  916,  917,  920,  929,
        930,  933,  937,  939,  941,  943,  948,  949,  951,  952,  953,
        956,  957,  958,  960,  962,  963,  964,  966,  968,  969,  970,
        973,  975,  976,  977,  979,  980,  981,  983,  985,  987,  988,
        989,  991,  994,  995,  996,  997, 1000, 1003, 1004, 1006, 1010,
       1012, 1013, 1015, 1016, 1017, 1019, 1021, 1022, 1025, 1033, 1034,
       1035, 1036, 1037, 1038, 1039, 1043, 1044, 1047, 1049, 1051, 1052,
       1057, 1058, 1061, 1062, 1063, 1064, 1069, 1070, 1075, 1076, 1078,
       1079, 1080, 1082, 1086, 1087, 1088, 1091, 1092, 1096, 1097, 1098,
       1101, 1104, 1106, 1107, 1109, 1110, 1111, 1113, 1114, 1116, 1123,
       1126, 1134, 1138, 1139, 1144, 1146, 1149, 1150, 1151, 1153, 1154,
       1155, 1157, 1158, 1159, 1160, 1163, 1165, 1166, 1168, 1169, 1170,
       1171, 1175, 1176, 1185, 1188, 1189, 1191, 1193, 1196, 1199, 1200,
       1203, 1206, 1208, 1209, 1214, 1218, 1221, 1222, 1223, 1224, 1228,
       1232, 1233, 1234, 1238, 1239, 1243, 1244, 1248, 1252, 1253, 1255,
       1257, 1269, 1270, 1273, 1276, 1279, 1280, 1282, 1283, 1284, 1286,
       1287, 1289, 1292, 1294, 1296, 1297, 1301, 1302, 1304, 1311, 1313,
       1316, 1317, 1322, 1323, 1328, 1331, 1334, 1337, 1339, 1343, 1344,
       1350, 1353, 1356, 1357, 1360, 1361, 1362, 1364, 1366, 1368, 1370,
       1381, 1382, 1383, 1384, 1385, 1386, 1387, 1388, 1391, 1392, 1394,
       1397, 1398, 1400, 1403, 1408, 1409, 1410, 1411, 1412, 1413, 1415,
       1418, 1422, 1424, 1425, 1426, 1428, 1429, 1434, 1435, 1440, 1443,
       1444, 1445, 1451, 1453, 1455, 1456, 1458, 1460, 1461, 1462, 1470,
       1472, 1473, 1474, 1476, 1477, 1480, 1483, 1486, 1492, 1493, 1495,
       1496, 1497, 1499, 1501, 1502, 1508, 1511, 1512, 1513, 1514, 1518,
       1519, 1521, 1522, 1523, 1526, 1531, 1534, 1538, 1539, 1540, 1544,
       1545, 1546, 1547, 1550, 1551, 1553, 1554, 1561, 1567, 1571, 1577,
       1583, 1586, 1587, 1588, 1589, 1594, 1601, 1607, 1611, 1613, 1614,
       1615, 1619, 1625, 1627, 1632, 1633, 1636, 1639, 1643, 1646, 1647,
       1648, 1655, 1656, 1657, 1659, 1660, 1661, 1662, 1663, 1664, 1667,
       1672, 1673, 1674, 1677, 1680, 1681, 1684, 1686, 1688, 1692, 1695,
       1696, 1699, 1700, 1701, 1703, 1706, 1708, 1710, 1713, 1715, 1716,
       1717, 1718, 1720, 1723, 1724, 1725, 1726, 1728, 1730, 1731, 1733,
       1735, 1736, 1737, 1739, 1742, 1744, 1745, 1747, 1748, 1749, 1750,
       1751, 1754, 1756, 1760, 1764, 1765, 1766, 1768, 1770, 1772, 1773,
       1775, 1780, 1781, 1782, 1784, 1786, 1788, 1789, 1790, 1791, 1792,
       1793, 1796, 1798, 1802, 1805, 1810, 1811, 1812, 1815, 1820, 1822,
       1824, 1825, 1829, 1830, 1833, 1834])

In [25]:
len(chipo[chipo["unit_price"]>10]["order_id"].unique())

787

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [27]:
orders_sum = chipo.groupby("order_id")["item_price"].sum()
orders_sum

order_id
1       11.56
2       16.98
3       12.67
4       21.00
5       13.70
        ...
1830    23.00
1831    12.90
1832    13.20
1833    23.50
1834    28.75
Name: item_price, Length: 1834, dtype: float64

In [28]:
len(orders_sum[orders_sum>10])

1834

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [29]:
chipo[chipo["item_price"]>10]

,order_id,quantity,item_name,choice_description,item_price,unit_price
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98,8.49
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98,10.98
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75,11.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25,11.25
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98,10.98
...,...,...,...,...,...,...
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25,11.25
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25,11.25

In [31]:
chipo[chipo["item_price"]>10]["order_id"].nunique()

863

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [32]:
chipo.loc[:,['item_name','unit_price']]

                                  item_name  unit_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl        8.49
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [33]:
chipo.sort_values("item_name",ascending=False)

,order_id,quantity,item_name,choice_description,item_price,unit_price
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98,8.49
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49,8.49
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49,8.49
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75,8.75
...,...,...,...,...,...,...
1916,774,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1124,465,1,6 Pack Soft Drink,[Coke],6.49,6.49
3789,1517,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
1392,566,1,6 Pack Soft Drink,[Diet Coke],6.49,6.49
3614,1448,1,6 Pack Soft Drink,[Nestea],6.49,6.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [39]:
max_valued_products = chipo[chipo['unit_price'] == chipo['unit_price'].max()]['item_name'].unique()
max_valued_products

<StringArray>
['Steak Salad Bowl', 'Carnitas Salad Bowl', 'Barbacoa Salad Bowl']
Length: 3, dtype: str

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [40]:
chipo[chipo["item_name"]=="Veggie Salad Bowl"]["quantity"].sum()

np.int64(18)

### Step 9. How many times did someone order more than one Canned Soda?

In [41]:
chipo[(chipo["item_name"]=="Canned Soda") & (chipo["quantity"] > 1)]['order_id'].nunique()

18